config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  get 'table', to: 'home#table', as: 'table'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exchange_rate.rb
# frozen_string_literal: true

class ExchangeRate < ApplicationRecord
  validates :date, :rub_to_usd, :rub_to_eur, :rub_to_cny, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    exchange_rates = ExchangeRate.order(:date).last(28)
    @graph_data = ExchangeGraphService.execute(exchange_rates)
  end

  def table
    exchange_week = ExchangeRate.order(date: :asc).limit(28).each_slice(7)

    @rub_to_usd = ExchangeTableService.new.execute(exchange_week:, valute: :rub_to_usd)
    @rub_to_eur = ExchangeTableService.new.execute(exchange_week:, valute: :rub_to_eur)
    @rub_to_cny = ExchangeTableService.new.execute(exchange_week:, valute: :rub_to_cny)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<div id="graph"></div>

<div class="text-center">
  <%= link_to 'К таблице', table_path %>
</div>


<script>
  let dates = <%= @graph_data.map { |graph| graph[:date] }.to_json.html_safe %>;
  let rubToUsd = <%= @graph_data.map { |graph| graph[:rub_to_usd] }.to_json.html_safe %>;
  let rubToEur = <%= @graph_data.map { |graph| graph[:rub_to_eur] }.to_json.html_safe %>;
  let rubToCny = <%= @graph_data.map { |graph| graph[:rub_to_cny] }.to_json.html_safe %>;

  let graph = c3.generate({
    bindto: '#graph',
    data: {
      date: 'DATE',
      columns: [
        ['DATE'].concat(dates),
        ['USD'].concat(rubToUsd),
        ['EUR'].concat(rubToEur),
        ['CNY'].concat(rubToCny)
      ],
      xFormat: '%d-%m-%y'
    },
  })
</script>

app/views/home/table.html.erb
<h1>Курс за последние 4 недели</h1>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Валюта</th>
    <th>4 недели назад</th>
    <th>3 недели назад</th>
    <th>позапрошлая неделя</th>
    <th>прошлая неделя</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>USD</td>
    <% @rub_to_usd.each do |week| %>
      <td><%= week.first %> (<%= week.last %>)</td>
    <% end %>
  </tr>
  <tr>
    <td>EUR</td>
    <% @rub_to_eur.each do |week| %>
      <td><%= week.first %> (<%= week.last %>)</td>
    <% end %>
  </tr>
  <tr>
    <td>CNY</td>
    <% @rub_to_cny.each do |week| %>
      <td><%= week.first %> (<%= week.last %>)</td>
    <% end %>
  </tr>
  </tbody>
</table>
<div class="text-center">
  <%= link_to 'График', root_path, data: { turbo:false }%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExchangeApp</title>
    <%= Gon::Base.render_data %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.20/c3.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.7.20/c3.min.css" rel="stylesheet">
  </head>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>